### ISSUE TITLE
Same workflow with ReactingFoam?

### ISSUE THREAD

**Issue by ndkazu** [airshaper/adaptive-mesh-refinement#1]
Hello, 
Do you have any advice for the implementation of this workflow to a simulation using _**reactingFoam**_ & _**OF-v2112**_?

**Comment by wouterremmerie** [comment]
That should indeed be possible. The refinement just needs a certain flow parameter to calculate the refinement criterium.
now it's gradP or curlU, but it can be modified to use chemical parameters as well.

So replacing the simpleFoam part with reactingFoam should work (we haven't worked with reactingFoam ourselves, so can't give more specific advice).
